/home/tsuguil/code/soccerscout/data/src/estimatingProbabilities.py:40: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[f'predicted{l}']=models[l].predict(pools[l])
id                    object
Period                 int64
Time                   int64
Start_x              float64
Start_y              float64
                      ...   
action_clearance       int64
action_bad_touch       int64
action_non_action      int64
action_dribble         int64
action_goalkick        int64
Length: 201, dtype: object
0       False
1       False
2       False
3       False
4       False
        ...  
2741    False
2742    False
2743    False
2744    False
2745    False
Name: predictedScores, Length: 2746, dtype: object
Index(['id', 'Period', 'Time', 'Start_x', 'Start_y', 'End_x', 'End_y',
       'Player', 'Team', 'Type_name',
       ...
       'action_keeper_punch', 'action_keeper_pick_up', 'action_clearance',
       'action_bad_touch', 'action_non_action', 'action_dribble',
       'action_goalkick', 'Scores', 'Concedes', 'predictedScores'],
      dtype='object', length=204)
id                    object
Period                 int64
Time                   int64
Start_x              float64
Start_y              float64
                      ...   
action_bad_touch       int64
action_non_action      int64
action_dribble         int64
action_goalkick        int64
predictedScores       object
Length: 202, dtype: object
Traceback (most recent call last):
  File "_catboost.pyx", line 2309, in _catboost.get_float_feature
  File "_catboost.pyx", line 1142, in _catboost._FloatOrNan
  File "_catboost.pyx", line 952, in _catboost._FloatOrNanFromString
TypeError: Cannot convert 'b'False'' to float

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tsuguil/code/soccerscout/data/src/estimatingProbabilities.py", line 58, in <module>
    listProcData(path)
  File "/home/tsuguil/code/soccerscout/data/src/estimatingProbabilities.py", line 53, in listProcData
    listProcData(subPath)
  File "/home/tsuguil/code/soccerscout/data/src/estimatingProbabilities.py", line 53, in listProcData
    listProcData(subPath)
  File "/home/tsuguil/code/soccerscout/data/src/estimatingProbabilities.py", line 53, in listProcData
    listProcData(subPath)
  [Previous line repeated 1 more time]
  File "/home/tsuguil/code/soccerscout/data/src/estimatingProbabilities.py", line 56, in listProcData
    calculateProbabilities(path+'/'+item, models)
  File "/home/tsuguil/code/soccerscout/data/src/estimatingProbabilities.py", line 38, in calculateProbabilities
    pool = Pool(data=data, label=df[l], cat_features=string_features)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tsuguil/code/soccerscout/data/venv/lib/python3.11/site-packages/catboost/core.py", line 793, in __init__
    self._init(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
  File "/home/tsuguil/code/soccerscout/data/venv/lib/python3.11/site-packages/catboost/core.py", line 1425, in _init
    self._init_pool(data, label, cat_features, text_features, embedding_features, embedding_features_data, pairs, weight,
  File "_catboost.pyx", line 3976, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 4026, in _catboost._PoolBase._init_pool
  File "_catboost.pyx", line 3842, in _catboost._PoolBase._init_features_order_layout_pool
  File "_catboost.pyx", line 2808, in _catboost._set_features_order_data_pd_data_frame
  File "_catboost.pyx", line 2350, in _catboost.create_num_factor_data
  File "_catboost.pyx", line 2311, in _catboost.get_float_feature
_catboost.CatBoostError: Bad value for num_feature[non_default_doc_idx=0,feature_idx=201]="False": Cannot convert 'b'False'' to float
